version: "3.8"

services:
  api-ugc:
    image: api-ugc
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-ugc
    command: >
      python main.py
    volumes:
      - ./src:/code
    ports:
      - 8000:8000
    env_file:
      - .dev.env
    restart: always

  nginx_ugc:
    container_name: nginx_ugc
    image: nginx:1.21.1
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - api-ugc

networks:
  default:
    name: kafka_default