version: "3.8"

services:
  ugc_etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ugc-etl
    command: >
      python app.py
    volumes:
      - "./:/app/etl"
    ports:
      - "5000:8000"
    env_file:
      - .env.dev

networks:
    default:
      name: kafka_default
